parameters:
    sfynx.translator.subscriber.word.class: Sfynx\TranslatorBundle\EventSubscriber\WordSubscriber

services:
    #
    # configuration of the event subscriber of position
    #         
    sfynx.translator.subscriber.word:
        class: %sfynx.translator.subscriber.word.class%
        arguments: [@service_container]
        tags:
            - { name: doctrine.event_subscriber, connexion: default  }                       